---
title: "Homework 1 for Data Science I"
author: "Tatini Mal-Sarkar"
date: "September 14, 2018"
output: github_document
---

```{r load_tidyverse, include = FALSE }
##load tidyverse 
library(tidyverse)
```

```{r p1}
##set seed for reproducibility's sake
set.seed(12)

##create dataframe with appropriate variables for problem 1
prob1_df = tibble(
  p1_random_samp = runif(10, min = 0, max = 5),
  p1_log_vec = p1_random_samp > 2,
  p1_char_vec = c('a','b','c','d','e','f','g','h','i','j'),
  p1_fac_vec = factor(p1_char_vec)
)

##try to take mean of each variable in dataframe prob1_df
##returns N/A for char_vec and fac_vec because the elements are neither numerical nor logical
mean(prob1_df$p1_random_samp)
mean(prob1_df$p1_log_vec)
mean(prob1_df$p1_char_vec)
mean(prob1_df$p1_fac_vec)
```

```{r p1_conv_num, results = 'hide'}
##convert logical, character, and factor variables to numeric
##my logical variable and factor variable have been converted to numeric, but an error tells me N/A forced by coercion for my character variable
as.numeric(prob1_df$p1_log_vec)
as.numeric(prob1_df$p1_char_vec)
as.numeric(prob1_df$p1_fac_vec)
```

```{r p1_conv_cfn_fcn, results = 'hide'}
##convert character to factor to numeric
##this successfully converts
as.numeric(as.factor(prob1_df$p1_char_vec))
##convert factor to character to numeric
##all elements become NA. An error says they are introduced by coercion.
as.numeric((as.character(prob1_df$p1_fac_vec)))
```

```{r p2}
##set seed for reproducibility's sake
set.seed(903)

##create dataframe with appropriate variables for problem 2
prob2_df = tibble(
  x = rnorm(1000),
  y = rnorm(1000),
  p2_log_vec = x + y > 0,
  p2_num_vec = as.numeric(p2_log_vec),
  p2_fac_vec = as.factor(p2_log_vec)
)
```

##short description of dataframe prob2_df
The **size** of the dataset `prob2_df` is `r nrow(prob2_df) * ncol(prob2_df)` observations.
The **mean** and **median** of x are `r mean(prob2_df$x)` and `r median(prob2_df$x)`, respectively.
The proportion of cases where the logical vector is **true** is `r sum(prob2_df$p2_log_vec) / nrow(prob2_df)`.